baseURL                = "https://hesheng-asher.github.io/hugo-main/"
locale                 = "zh-cn"
title                  = "Hugo \u4e3b\u9898 Stack"
defaultContentLanguage = "zh"
hasCJKLanguage         = true

[pagination]
    pagerSize = 3

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "hugo-theme-stack"
