baseURL                = "https://hesheng-asher.github.io/"
locale                 = "zh-cn"
title = "Hesheng Blog"
defaultContentLanguage = "zh"
hasCJKLanguage         = true

[pagination]
    pagerSize = 3

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "heshengblog"
