mainSections   = ["post"]
rssFullContent = true
favicon        = "img/avatar.png"

[footer]
    since = 2026

[sidebar]
    subtitle = "技术分享与生活随笔"
    avatar   = "img/avatar.png"

[article]
    [article.license]
        enabled = true
        default = "Licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

[widgets]
    homepage = [
        { type = "archives", params = { limit = 5 } },
    ]
    page     = [{ type = "toc" }]

[comments]
    enabled  = true
    provider = "giscus"

[cookies]
    enabled = false

    [cookies.categories]
        analytics  = true
        functional = true

[comments.giscus]
    repo = "Hesheng-Asher/hesheng-asher.github.io"
    repoID = "R_kgDOSh-0vA"
    category = "Announcements"
    categoryID = "DIC_kwDOSh-0vM4C9eEc"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    lightTheme = "preferred_color_scheme"
    darkTheme = "preferred_color_scheme"
    lang = "zh-CN"
    loading = "lazy"
