backend:
  name: github
  repo: Hesheng-Asher/hesheng-asher.github.io
  branch: main
  open_authoring: true
  publish_mode: editorial_workflow

locale: zh_Hans

site_url: https://hesheng-asher.github.io/
display_url: https://hesheng-asher.github.io/
logo_url: /img/avatar.png

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "文章"
    label_singular: "文章"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{slug}}/index.zh"
    media_folder: ""
    public_folder: ""
    summary: "{{title}}"
    editor:
      preview: false
    fields:
      - label: "标题"
        name: "title"
        widget: "string"
      - label: "发布日期"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
        time_format: false
      - label: "描述"
        name: "description"
        widget: "text"
        required: false
      - label: "封面图"
        name: "image"
        widget: "image"
        required: false
      - label: "分类"
        name: "categories"
        widget: "select"
        required: false
        multiple: true
        options:
          - "文档"
      - label: "标签"
        name: "tags"
        widget: "select"
        required: false
        multiple: true
        options:
          - "隐私"
          - "Markdown 语法"
          - "样式"
          - "网页"
          - "主题"
          - "相册"
          - "图片灯箱"
      - label: "草稿（不发布）"
        name: "draft"
        widget: "boolean"
        default: false
        required: false
      - label: "正文"
        name: "body"
        widget: "markdown"

  - name: "pages"
    label: "页面"
    editor:
      preview: false
    files:
      - name: "home"
        label: "首页"
        file: "content/_index.zh.md"
        fields:
          - label: "菜单"
            name: "menu"
            widget: "object"
            required: false
            collapsed: true
            fields:
              - label: "主菜单"
                name: "main"
                widget: "object"
                required: false
                fields:
                  - label: "名称"
                    name: "name"
                    widget: "string"
                    required: false
                  - label: "排序权重"
                    name: "weight"
                    widget: "number"
                    value_type: "int"
                    required: false
                  - label: "参数"
                    name: "params"
                    widget: "object"
                    required: false
                    fields:
                      - label: "图标"
                        name: "icon"
                        widget: "string"
                        required: false
          - label: "正文"
            name: "body"
            widget: "markdown"
            required: false

      - name: "about"
        label: "关于"
        file: "content/page/about/index.zh.md"
        fields:
          - label: "标题"
            name: "title"
            widget: "string"
          - label: "描述"
            name: "description"
            widget: "text"
            required: false
          - label: "日期"
            name: "date"
            widget: "datetime"
            format: "YYYY-MM-DD"
            date_format: "YYYY-MM-DD"
            time_format: false
          - label: "最后修改"
            name: "lastmod"
            widget: "datetime"
            format: "YYYY-MM-DD"
            date_format: "YYYY-MM-DD"
            time_format: false
          - label: "菜单"
            name: "menu"
            widget: "object"
            required: false
            collapsed: true
            fields:
              - label: "主菜单"
                name: "main"
                widget: "object"
                required: false
                fields:
                  - label: "名称"
                    name: "name"
                    widget: "string"
                    required: false
                  - label: "排序权重"
                    name: "weight"
                    widget: "number"
                    value_type: "int"
                    required: false
                  - label: "参数"
                    name: "params"
                    widget: "object"
                    required: false
                    fields:
                      - label: "图标"
                        name: "icon"
                        widget: "string"
                        required: false
          - label: "正文"
            name: "body"
            widget: "markdown"

      - name: "links"
        label: "链接"
        file: "content/page/links/index.zh.md"
        fields:
          - label: "标题"
            name: "title"
            widget: "string"
          - label: "链接列表"
            name: "links"
            widget: "list"
            required: false
            fields:
              - label: "标题"
                name: "title"
                widget: "string"
              - label: "描述"
                name: "description"
                widget: "text"
                required: false
              - label: "网站"
                name: "website"
                widget: "string"
              - label: "图片"
                name: "image"
                widget: "image"
                required: false
          - label: "菜单"
            name: "menu"
            widget: "object"
            required: false
            collapsed: true
            fields:
              - label: "主菜单"
                name: "main"
                widget: "object"
                required: false
                fields:
                  - label: "名称"
                    name: "name"
                    widget: "string"
                    required: false
                  - label: "排序权重"
                    name: "weight"
                    widget: "number"
                    value_type: "int"
                    required: false
                  - label: "参数"
                    name: "params"
                    widget: "object"
                    required: false
                    fields:
                      - label: "图标"
                        name: "icon"
                        widget: "string"
                        required: false
          - label: "评论"
            name: "comments"
            widget: "boolean"
            required: false
          - label: "正文"
            name: "body"
            widget: "markdown"
            required: false

      - name: "archives"
        label: "归档"
        file: "content/page/archives/index.zh.md"
        fields:
          - label: "标题"
            name: "title"
            widget: "string"
          - label: "日期"
            name: "date"
            widget: "datetime"
            format: "YYYY-MM-DD"
            date_format: "YYYY-MM-DD"
            time_format: false
          - label: "布局"
            name: "layout"
            widget: "hidden"
            default: "archives"
          - label: "别名"
            name: "slug"
            widget: "hidden"
            default: "archives"
          - label: "菜单"
            name: "menu"
            widget: "object"
            required: false
            collapsed: true
            fields:
              - label: "主菜单"
                name: "main"
                widget: "object"
                required: false
                fields:
                  - label: "名称"
                    name: "name"
                    widget: "string"
                    required: false
                  - label: "排序权重"
                    name: "weight"
                    widget: "number"
                    value_type: "int"
                    required: false
                  - label: "参数"
                    name: "params"
                    widget: "object"
                    required: false
                    fields:
                      - label: "图标"
                        name: "icon"
                        widget: "string"
                        required: false
          - label: "正文"
            name: "body"
            widget: "markdown"
            required: false